### ISSUE TITLE
question real world use case

### ISSUE THREAD

**Issue by ghost** [ricardocrescenti/flutter-entity-model-structure#2]
Hi @ricardocrescenti  ,

Hope you are all well !

I am just dropping this message as I would like to create a teampass (https://teampass.net/) clone with flutter.

What would you advice me to use as an architecture for managing permission rights to items categories with view/edit/delete capability per categories or items. I found [flutter_rbac](https://github.com/wilpar/flutter_rbac) or [dart-casbin](https://github.com/casbin/dart-casbin) and [animated_tree_view](https://github.com/embraceitmobile/animated_tree_view)

Screenshot of teampass:
![pf_tp_5](https://user-images.githubusercontent.com/1963546/143861629-3a6c67c6-c11b-492b-a96a-5714bddbc5bb.png)

The bottleneck I see, is that have I have 30k items to hook in the the tree view. Is It possible to make the tree view searchable ?

Do you think that flutter-entity-model-structure can be a good core ?

Thanks for any insights or inputs to help me to boostrap this project.

Cheers,
Luc

**Comment by ricardocrescenti** [comment]
hello @lucmichalski

The flutter-entity-model-structure is a project where I developed a data structure standard for managing users and permissions, it doesn't provide a list in trees as you need it, but it could be used as a data structure for the managing the permissions of each folder.

You would have to modify the PermissionModelPattern to receive the folder ID, along with the permissions the user will have on the folder.

Regarding the number of items, I would load the data on demand, that is, when opening the application, I would load only the initial level items, and when clicking on the folder, I would load the child items of the selected folder, in this way the application would open faster and consume less memory. To know when a folder has children without querying the database, I would create a field indicating whether the folder has children or not, and I would update this field through a trigger, when an item is added inside, I would set the field to "true", and removing all would set it to "false", so you could put the icon to expand only on folders that have children. This field saves a lot of work from the database, otherwise it would be necessary to load the current items, and already load its children, and when you arrive at a time that has 30k folders, and 30k more children inside this folder, it would process a lot the application.

About the search, one possibility is to search all items and show in a new window, and when the user selects that item, you load only that selected item, at this moment, the customer can select a level 4 item, then you would have to get the parents of these items, stops after loading all these items in the main structure.


Thanks for the question, and sorry for the delay in answering and for my English.
graciously
Ricardo.
